name: snake-lips-2d
channels:
- defaults
dependencies:
- python >=3.7,<3.8
- pip
- h5py ==2.10.0
- lxml ==4.5.0
- matplotlib ==3.1.3
- numpy ==1.18.1
- pandas ==1.2.4
- pyyaml ==5.3.1
- scipy ==1.4.1
- pip:
  - git+https://github.com/mesnardo/petibmpy@v0.2
