batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  docker_images:
  - barbagroup/petibm:0.5.1-GPU-OpenMPI-xenial
  volumes:
    shared_data_volumes:
      azurefile_vol:
        volume_driver: azurefile
        storage_account_settings: mystorageaccount
        azure_file_share_name: fileshare
        container_path: $AZ_BATCH_NODE_SHARED_DIR/azfile
        mount_options:
        - file_mode=0777
        - dir_mode=0777
        bind_options: rw
