# 2628x1844 (4846032)
mesh:
- direction: x
  start: -15.0
  subDomains:
  - cells: 164
    end: -1.88
    stretchRatio: 1.0
  - cells: 33
    end: -1.0
    stretchRatio: 0.9090909091
  - cells: 2000
    end: 7.0
    stretchRatio: 1.0
  - cells: 302
    end: 14.68
    stretchRatio: 1.01
  - cells: 129
    end: 25.0
    stretchRatio: 1.0
- direction: y
  start: -15.0
  subDomains:
  - cells: 139
    end: -3.88
    stretchRatio: 1.0
  - cells: 33
    end: -3.0
    stretchRatio: 0.9090909091
  - cells: 1500
    end: 3.0
    stretchRatio: 1.0
  - cells: 33
    end: 3.88
    stretchRatio: 1.1
  - cells: 139
    end: 15.0
    stretchRatio: 1.0

flow:
  nu: 5e-4
  initialVelocity: [1.0, 0.0]
  boundaryConditions:
  - location: xMinus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
  - location: xPlus
    u: [CONVECTIVE, 1.0]
    v: [CONVECTIVE, 1.0]
  - location: yMinus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]
  - location: yPlus
    u: [DIRICHLET, 1.0]
    v: [DIRICHLET, 0.0]

parameters:
  dt: 0.0004
  startStep: 0
  nt: 200000
  nsave: 5000
  nrestart: 20000
  convection: ADAMS_BASHFORTH_2
  diffusion: CRANK_NICOLSON
  velocitySolver:
    type: CPU
    config: config/velocity_solver.info
  poissonSolver:
    type: GPU
    config: config/poisson_solver.info
  forcesSolver:
    type: CPU
    config: config/forces_solver.info

bodies:
- type: points
  name: snake
  file: snake.body
